spring:
  application:
    name: app-authenticator
    version: 1.0.0
    description: Authenticator Application
    team:
      name: Firefly Software Solutions Inc
      email: dev@getfirefly.io
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"